### ISSUE TITLE
Create/automate releases

### ISSUE THREAD

**Issue by orhun** [spicylobstergames/astratomic#10]
Hey,
I would like to add this game to [SpicyLauncher](https://github.com/spicylobstergames/SpicyLauncher)! 🦞 
For that, it would be nice to start creating releases (and automating them).
Is there any plans regarding that? I would be happy to help with the automated releases.

**Comment by Zac8668** [comment]
For sure! I've been a bit busy these days but probably soon we'll have a proper first release, just gotta fix some bugs, do you have some information on how can I get the automated releases up and running?

**Comment by orhun** [comment]
Absolutely, we can simply adopt the workflows from one of the other game projects:

- https://github.com/fishfolk/jumpy/blob/main/.github/workflows/release.yml
- https://github.com/fishfolk/punchy/blob/master/.github/workflows/cd.yml

Important part is the we follow the correct naming format for the assets (for launcher to pick up the correct assets):

- https://github.com/fishfolk/jumpy/blob/main/PACKAGING.md#binary-releases

Also, I wrote a blog post detailing some other ways of automating the releases, feel free to give it a read here: https://blog.orhun.dev/automated-rust-releases/

Just let me know when you are ready for a first release and we can cook something up together and add `astratomic` to the launcher 🚀

**Comment by Zac8668** [comment]
Not sure if I should have told you before to set up something with the launcher, but I saw the workflows from the other game projects and added them to Astratomic, and also made a first beta release, the assets are also on the `assets` folder, so I think we are good to go, @orhun right?

**Comment by orhun** [comment]
Thanks for setting up automated releases! I added Astratomic to the launcher in https://github.com/spicylobstergames/SpicyLauncher/pull/61
