### ISSUE TITLE
Add new types of atoms

### ISSUE THREAD

**Issue by Zac8668** [spicylobstergames/astratomic#33]
- [ ] #35 
- [ ] #34 
- [ ] #36 

- [ ] Add lava
- [ ] Dirt
- [ ] Stone
- [ ] Wood
- ...

**Comment by Zac8668** [comment]
On Astratomic we are looking for some more "realistic" types of atoms, something like the cloner, or something too abstract would not fit that well with the game.

**Comment by hallucino** [comment]
Is it in the roadmap to add more interactions between atoms ?

**Comment by Zac8668** [comment]
@hallucino For sure! There is just so much to do at the moment that we didn't add that yet.
