### ISSUE TITLE
Add particles

### ISSUE THREAD

**Issue by Zac8668** [spicylobstergames/astratomic#35]
Particles are really helpful, and game changer for visuals.

**Comment by erlend-sh** [comment]
Particles can mean different things in a falling-sand game, so are we talking about (1) regular, shader-based particles with no mass, or (2) actual atoms with inherent light sources?

I suppose there might be a mix of both. Related:
- #22 

For atom-less particles, there seems to be two reasonably mature options if we wanna go with a pre-made solution:

bevy_hanabi is a likely candidate. Its WASM support is still in progress, but it could just be toggled off in the browser until it works well: https://github.com/djeedai/bevy_hanabi/issues/41

The alternative is 2D-only and already WASM-friendly, which does seem promising: https://github.com/abnormalbrain/bevy_particle_systems

**Comment by Zac8668** [comment]
Particles are for sure ambiguous.
What I'm implementing right now is a simple entity that is visually equal to the normal atoms, it updates itself and when it collides with a normal atom it puts itself back on the normal atom simulation.

From what I'm testing bevy is dealing with them pretty well without a GPU approach, but we would probably want to speed that up in the future.
